nhs-digital-gp-it-futures/order-form

app/includes/header.njk, app/includes/header.test.js, package-lock.json, package.json
[AB#6363](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/6363)
[AB#6435](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/6435)
=> 6363: Add params to populate href and ariaLabel to logo

app/authProvider.js, app/config.js, app/pages/index/ui.test.js, app/routes.js, app/routes.test.js, app/server.js, package-lock.json, package.json
[AB#6440](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/6440)
=> 6101 update with claim type

app/config.js, docker-compose-redis.yml
[AB#6273](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/6273)
=> Change default local redis port to not clash with local cluster

README.md, app/config.js, app/pages/index/ui.test.js, app/routes.js, app/routes.test.js, app/server.js, app/test-utils/helper.js, package.json
[AB#6650](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/6650)
[AB#6505](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/6505)
=> 6101-change route

app/pages/index/ui.test.js, app/routes.js, app/routes.test.js
Story: [AB#4826](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/4826)
Task: [AB#6755](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/6755)
=> 4826: Add routes for / and /organisation

app/routes.js, app/routes.test.js
[AB#6763](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/6763)
=> 5111 - added neworder route

app/routes.js, app/routes.test.js
[AB#6773](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/6773)
=> 5322 route for description

app/routes.js, app/routes.test.js
[AB#6779](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/6779)
=> 5161 - existing order route

app/config.js, app/pages/dashboard/_dashboard.scss, app/pages/dashboard/contextCreator.js, app/pages/dashboard/contextCreator.test.js, app/pages/dashboard/controller.js, app/pages/dashboard/manifest.json, app/pages/dashboard/template.njk, app/pages/dashboard/template.test.js, app/pages/dashboard/ui.test.js, app/routes.js, app/styles/main.scss, app/test-utils/helper.js, package-lock.json, package.json
Story: [AB#4826](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/4826)
Task: [AB#6754](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/6754)
=> 4826: Create dashboard page

app/endpoints.js, app/pages/dashboard/contextCreator.js, app/pages/dashboard/contextCreator.test.js, app/pages/dashboard/controller.js, app/pages/dashboard/controller.test.js, app/pages/dashboard/ui.test.js, app/pages/order-task-list/neworder/ui.test.js, app/routes.js, app/routes.test.js, testcafeRunner.js
Story: [AB#4826](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/4826)
Task: [AB#6884](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/6884)
=> 4826: Update endpoint for dashboard

app/endpoints.js, app/pages/sections/description/contextCreator.js, app/pages/sections/description/contextCreator.test.js, app/pages/sections/description/controller.js, app/pages/sections/description/controller.test.js, app/pages/sections/description/existingorder.ui.test.js, app/pages/sections/description/neworder.ui.test.js, app/routes.js, app/routes.test.js
Story: [AB#5322](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/5322)
Task: [AB#6776](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/6776)
=> 5322: Add get description to populate description field

app/pages/sections/description/contextCreator.js, app/pages/sections/description/contextCreator.test.js, app/pages/sections/description/controller.js, app/pages/sections/description/controller.test.js, app/pages/sections/description/existingorder.ui.test.js, app/pages/sections/description/manifest.json, app/pages/sections/description/neworder.ui.test.js, app/pages/sections/description/template.njk, app/pages/sections/description/template.test.js, app/routes.js, app/routes.test.js, package-lock.json, package.json
Story: [AB#5322](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/5322)
Task: [AB#6775](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/6775)
=> 5322: Add validation for description

app/routes.test.js
Story: [AB#6729](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/6729)
Task: [AB#6984](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/6984)
=> 6729: Add unauthorised users tests get routes

app/pages/task-list/existingorder/ui.test.js, package-lock.json, package.json
[AB#7042](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/7042)
=> bump bcc version

package-lock.json, package.json
[AB#7059](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/7059)
=> 6727 - disable healthcheck logs

app/routes.js, app/routes.test.js
Story: [AB#4615](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/4615)
Task: [AB#7083](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/7083)
=> 4615: Add call-off-ordering-party route

app/pages/task-list/existingorder/ui.test.js, app/pages/task-list/neworder/ui.test.js, app/pages/task-list/taskListManifest.json
Story [AB#4620](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/4620)
Tasks [AB#7094](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/7094) [AB#7095](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/7095)
=> 4620-updated task-list manifest and ui-tests

app/routes.js, app/routes.test.js
Story [AB#4840](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/4840)
Task [AB#7097](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/7097)
=> 4840 - add route for supplier that redirects to /search

app/endpoints.js, app/pages/sections/call-off-ordering-party/controller.js, app/pages/sections/call-off-ordering-party/controller.test.js, app/pages/sections/call-off-ordering-party/ui.test.js, app/routes.test.js
STORY: [AB#4615](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/4615)
TASK: [AB#7085](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/7085)
=> 4615: Add get for call off ordering party

app/config.js, app/endpoints.js, app/pages/sections/call-off-ordering-party/controller.js, app/pages/sections/call-off-ordering-party/controller.test.js, app/routes.js
Story: [AB#4615](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/4615)
Task [AB#7086](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/7086)
=> 4615: Call oapi for org data

app/helpers/createAuthProvider.js, package-lock.json, package.json
Story: [AB#4615](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/4615)
Task: [AB#7208](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/7208)
=> 4615: Amend scopes

app/pages/sections/call-off-ordering-party/controller.js, app/pages/sections/call-off-ordering-party/controller.test.js, app/pages/sections/call-off-ordering-party/manifest.json, app/pages/sections/call-off-ordering-party/template.njk, app/pages/sections/call-off-ordering-party/template.test.js, app/pages/sections/call-off-ordering-party/ui.test.js, app/pages/sections/description/contextCreator.test.js, app/pages/sections/description/manifest.json
Task: [AB#7089](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/7089)
=> 4616: Add primary contact form

app/endpoints.js, app/pages/sections/call-off-ordering-party/controller.js, app/pages/sections/call-off-ordering-party/controller.test.js, app/pages/sections/call-off-ordering-party/template.njk, app/pages/sections/call-off-ordering-party/template.test.js, app/pages/sections/call-off-ordering-party/ui.test.js, app/pages/sections/description/controller.js, app/pages/sections/description/controller.test.js, app/routes.js, app/routes.test.js
Task: [AB#7090](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/7090)
=> 4616: Save data

app/pages/sections/call-off-ordering-party/contextCreator.js, app/pages/sections/call-off-ordering-party/contextCreator.test.js, app/pages/sections/call-off-ordering-party/controller.js, app/pages/sections/call-off-ordering-party/controller.test.js, package-lock.json, package.json
Task: [AB#7092](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/7092)
=> 4616: Populate primary data fields

app/pages/dashboard/contextCreator.test.js, app/pages/dashboard/manifest.json, app/pages/dashboard/template.njk, app/pages/sections/call-off-ordering-party/contextCreator.js, app/pages/sections/call-off-ordering-party/contextCreator.test.js, app/pages/sections/call-off-ordering-party/controller.js, app/pages/sections/call-off-ordering-party/controller.test.js, app/pages/sections/call-off-ordering-party/manifest.json, app/pages/sections/call-off-ordering-party/template.njk, app/pages/sections/call-off-ordering-party/template.test.js, app/pages/sections/call-off-ordering-party/ui.test.js, app/pages/sections/description/contextCreator.js, app/pages/sections/description/contextCreator.test.js, app/pages/sections/description/existingorder.ui.test.js, app/pages/sections/description/manifest.json, app/pages/sections/description/neworder.ui.test.js, app/pages/sections/description/template.njk, app/pages/sections/description/template.test.js, app/pages/sections/getSectionErrorContext.js, app/pages/sections/getSectionErrorContext.test.js, app/pages/sections/supplier/search/contextCreator.js, app/pages/sections/supplier/search/contextCreator.test.js, app/pages/sections/supplier/search/ui.test.js, app/routes.js, app/routes.test.js
Task: [AB#7091](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/7091)
=> 4616: Validation

app/pages/sections/description/controller.js, app/pages/sections/description/controller.test.js
Task: [AB#7133](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/7133)
=> 4616: Trim description before put

app/pages/task-list/existingorder/ui.test.js, app/pages/task-list/helpers/generateTaskList.js, app/pages/task-list/neworder/ui.test.js, app/pages/task-list/taskListManifest.json
Story: AB#4617
Tasks: AB#7121 AB#7122
=> 4617: Add commencement date to tasklist

app/pages/sections/commencement-date/contextCreator.js, app/pages/sections/commencement-date/contextCreator.test.js, app/pages/sections/commencement-date/controller.js, app/pages/sections/commencement-date/manifest.json, app/pages/sections/commencement-date/template.njk, app/pages/sections/commencement-date/template.test.js, app/pages/sections/routes.js, app/pages/sections/routes.test.js
Story: [AB#4619](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/4619)
Task: [AB#7124](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/7124)
=> 4619: Commencement date page

app/endpoints.js, app/pages/sections/call-off-ordering-party/controller.js, app/pages/sections/call-off-ordering-party/controller.test.js, app/pages/sections/commencement-date/controller.js, app/pages/sections/commencement-date/controller.test.js, app/pages/sections/routes.js
Story: [AB#4619](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/4619)
Task: [AB#7129](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/7129)
=> 4619: Save data

package-lock.json, package.json
Bug: [AB#7343](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/7343)
Task: [AB#7363](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/7363)
=> 7343: Bump bcc to fix beta banner bug

app/pages/sections/commencement-date/contextCreator.js, app/pages/sections/commencement-date/contextCreator.test.js, app/pages/sections/commencement-date/controller.js, app/pages/sections/commencement-date/controller.test.js, app/pages/sections/commencement-date/template.njk, app/pages/sections/commencement-date/template.test.js, app/pages/sections/routes.js, app/pages/sections/routes.test.js
Story: [AB#4619](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/4619)
Task: [AB#7126](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/7126)
=> 4619: Add be validation

app/pages/sections/call-off-ordering-party/controller.js, app/pages/sections/call-off-ordering-party/controller.test.js, app/pages/sections/call-off-ordering-party/template.njk, app/pages/sections/call-off-ordering-party/template.test.js, app/pages/sections/routes.test.js, app/pages/sections/supplier/routes.test.js
changed to expect {} not 404 as thought
Story: [AB#4615](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/4615)
Task: [AB#7373](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/7373)
=> 4615: Fix data pull through

app/pages/sections/commencement-date/contextCreator.test.js, app/pages/sections/commencement-date/controller.js, app/pages/sections/commencement-date/controller.test.js, app/pages/sections/commencement-date/getDateErrors.test.js, app/pages/sections/commencement-date/manifest.json
Story: [AB#4619](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/4619)
Task: [AB#7378](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/7378)
=> 4619: Update dates with leading 0 if single digit

.gitignore, azure-pipelines.yml, charts/of/.helmignore, charts/of/Chart.yaml, charts/of/templates/NOTES.txt, charts/of/templates/_helpers.tpl, charts/of/templates/deployment.yaml, charts/of/templates/ingress.yaml, charts/of/templates/service.yaml, charts/of/templates/serviceaccount.yaml, charts/of/templates/tests/test-connection.yaml, charts/of/values.yaml
[AB#7000](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/7000)
=> Add semantic versioning and helm chart

app/pages/sections/supplier/supplier/contextCreator.js, app/pages/sections/supplier/supplier/contextCreator.test.js, app/pages/sections/supplier/supplier/controller.js, app/pages/sections/supplier/supplier/controller.test.js, app/pages/sections/supplier/supplier/template.njk, app/pages/sections/supplier/supplier/template.test.js
Story: [AB#6916](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/6916)
Task: [AB#7118](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/7118)
=> 6916: Hide search again link

app/pages/sections/supplier/supplier/contextCreator.js, app/pages/sections/supplier/supplier/contextCreator.test.js, app/pages/sections/supplier/supplier/ui.test.js
Story: [AB#6916](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/6916)
Task: [AB#7119](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/7119)
=> 6919: Construct correct backlink for saved data

app/pages/sections/call-off-ordering-party/ui.test.js, app/pages/sections/supplier/supplier/ui.test.js
Story: [AB#7103](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/7103)
Task: [AB#7406](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/7406)
=> 7103: Improve ui tests for call off ordering party section

app/pages/task-list/existingorder/ui.test.js, app/pages/task-list/neworder/ui.test.js, app/pages/task-list/taskListManifest.json
Story: [AB#4623](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/4623)
Task: [AB#7502](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/7502)
=> 4623: Add service recipient to task list

app/pages/sections/routes.js, app/pages/sections/routes.test.js, app/pages/sections/service-recipients/contextCreator.js, app/pages/sections/service-recipients/contextCreator.test.js, app/pages/sections/service-recipients/controller.js, app/pages/sections/service-recipients/manifest.json, app/pages/sections/service-recipients/template.njk, app/pages/sections/service-recipients/template.test.js, package-lock.json
Story: [AB#4623](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/4623)
Task: [AB#7504](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/7504)
=> 4623: Add service recipient page

app/endpoints.js, app/pages/sections/routes.js, app/pages/sections/routes.test.js, app/pages/sections/service-recipients/controller.js, app/pages/sections/service-recipients/controller.test.js, package-lock.json
Story [AB#7412](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/7412)
Task [AB#7506](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/7506)
=> 7506 call to oapi

app/endpoints.js, app/pages/sections/supplier/search/controller.test.js, app/pages/sections/supplier/search/ui.test.js
Story [AB#7411](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/7411)
Task [AB#7497](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/7497)
=> update supplier search endpoint

app/endpoints.js, app/pages/sections/service-recipients/controller.js, app/pages/sections/service-recipients/controller.test.js, package-lock.json
Story: [AB#7412](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/7412)
Task: [AB#7507](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/7507)
=> 7412: Add ordapi get

app/pages/dashboard/_dashboard.scss, app/pages/dashboard/template.njk, app/pages/sections/catalogue-solutions/catalogue-solutions/template.njk, app/pages/sections/ordering-party/template.njk, app/pages/sections/service-recipients/_service-recipients.scss, app/pages/sections/service-recipients/contextCreator.js, app/pages/sections/service-recipients/contextCreator.test.js, app/pages/sections/service-recipients/controller.js, app/pages/sections/service-recipients/controller.test.js, app/pages/sections/service-recipients/template.njk, app/pages/sections/service-recipients/template.test.js, app/pages/sections/service-recipients/ui-tests/general.ui.test.js, app/pages/sections/supplier/supplier/template.njk, app/pages/task-list/template.njk, app/styles/main.scss
Story [AB#7412](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/7412)
Task [AB#7508](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/7508)
=> 7412 display service table

app/endpoints.js, app/pages/sections/commencement-date/contextCreator.js, app/pages/sections/commencement-date/ui.test.js, app/pages/sections/supplier/search/controller.test.js, app/pages/sections/supplier/search/ui.test.js
Commencement data bug fix
Story [AB#7577](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/7577)
Task [AB#7583](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/7583)
Supplier search endpoint fix
Story [AB#7411](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/7411)
Task [AB#7497](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/7497)
=> fix bug and update ui-tests

app/pages/dashboard/ui-tests/ui.test.js, app/pages/sections/commencement-date/ui-tests/ui.test.js, app/pages/sections/description/ui-tests/existingorder.ui.test.js, app/pages/sections/description/ui-tests/neworder.ui.test.js, app/pages/sections/ordering-party/ui-tests/ui.test.js, app/pages/sections/service-recipients/_service-recipients.scss, app/pages/sections/service-recipients/contextCreator.js, app/pages/sections/service-recipients/contextCreator.test.js, app/pages/sections/service-recipients/controller.js, app/pages/sections/service-recipients/controller.test.js, app/pages/sections/service-recipients/template.njk, app/pages/sections/service-recipients/ui-tests/general.ui.test.js, app/pages/sections/service-recipients/ui-tests/withSavedData.ui.test.js, app/pages/sections/service-recipients/ui-tests/withoutSavedData.ui.test.js, app/pages/sections/supplier/search/ui-tests/ui.test.js, app/pages/sections/supplier/select/ui-tests/ui.test.js, app/pages/sections/supplier/supplier/ui-tests/ui.test.js, app/pages/task-list/existingorder/ui-tests/ui.test.js, app/pages/task-list/neworder/ui-tests/ui.test.js, testcafeRunner.js
Story: [AB#7412](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/7412)
Task: [AB#7566](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/7566)
=> 7412: Populate checkboxes

app/endpoints.js, app/pages/sections/routes.js, app/pages/sections/routes.test.js, app/pages/sections/service-recipients/contextCreator.js, app/pages/sections/service-recipients/contextCreator.test.js, app/pages/sections/service-recipients/controller.js, app/pages/sections/service-recipients/controller.test.js, app/pages/sections/service-recipients/template.njk, app/pages/sections/service-recipients/template.test.js, app/pages/sections/service-recipients/ui-tests/general.ui.test.js, app/pages/sections/service-recipients/ui-tests/withSavedData.ui.test.js, app/pages/sections/service-recipients/ui-tests/withoutSavedData.ui.test.js
Story [AB#7412](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/7412)
Task [AB#7511](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/7511)
=> 7412 save button

app/endpoints.js, app/pages/sections/catalogue-solutions/routes.js, app/pages/sections/catalogue-solutions/routes.test.js, app/pages/sections/catalogue-solutions/select-price/controller.js, app/pages/sections/catalogue-solutions/select-price/controller.test.js
Story [AB#7260](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/7260)
Task [AB#7538](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/7538)
=> 7260 controller updated

app/endpoints.js, app/pages/sections/supplier/search/controller.test.js
Story [AB#7410](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/7410)
Task [AB#7618](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/7618)
=> encode the endpoints

app/pages/sections/commencement-date/ui-tests/general.ui.test.js, app/pages/sections/commencement-date/ui-tests/withSavedData.ui.test.js, app/pages/sections/description/ui-tests/existingorder.ui.test.js, app/pages/sections/description/ui-tests/general.ui.test.js, app/pages/sections/description/ui-tests/neworder.ui.test.js, app/pages/sections/ordering-party/ui-tests/general.ui.test.js, app/pages/sections/ordering-party/ui-tests/withSavedData.ui.test.js, app/pages/sections/ordering-party/ui-tests/withoutSavedData.ui.test.js, app/pages/sections/service-recipients/ui-tests/general.ui.test.js, app/pages/sections/service-recipients/ui-tests/withSavedData.ui.test.js, app/pages/sections/service-recipients/ui-tests/withoutSavedData.ui.test.js, app/pages/sections/supplier/supplier/ui-tests/withoutSavedData.ui.test.js, app/pages/task-list/existingorder/ui-tests/ui.test.js, app/pages/task-list/neworder/manifest.json, app/pages/task-list/neworder/ui-tests/ui.test.js
Story: [AB#7399](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/7399)
Task: [AB#7639](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/7639)
=> 7399: Update description content

app/pages/sections/catalogue-solutions/routes.js, app/pages/sections/catalogue-solutions/routes.test.js, app/pages/sections/catalogue-solutions/select-recipient/contextCreator.js, app/pages/sections/catalogue-solutions/select-recipient/contextCreator.test.js, app/pages/sections/catalogue-solutions/select-recipient/controller.js, app/pages/sections/catalogue-solutions/select-recipient/controller.test.js, app/pages/sections/catalogue-solutions/select-recipient/manifest.json, app/pages/sections/catalogue-solutions/select-recipient/template.njk, app/pages/sections/catalogue-solutions/select-recipient/template.test.js, app/pages/sections/catalogue-solutions/select-recipient/ui-tests/general.ui.test.js
Story [AB#7261](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/7261)
Task [AB#7644](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/7644)
=> basic select recipient page

app/config.js, app/documentController.js, app/documentController.test.js, app/endpoints.js, app/helpers/routerHelper.js, app/includes/header.njk, app/pages/sections/ordering-party/ui-tests/withoutSavedData.ui.test.js, app/routes.js, app/routes.test.js, package-lock.json, package.json
Story: [AB#7461](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/7461)
Task: [AB#7585](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/7585)
=> 7461: Remove blobstore

app/endpoints.js, app/pages/sections/supplier/search/controller.test.js
Story: [AB#7420](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/7420)
Task: [AB#7676](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/7676)
=> 7420: Fix url encoding

app/documentController.js, app/endpoints.js, app/helpers/isIdentityReady.js, app/helpers/routerHelper.js, app/pages/dashboard/controller.js, app/pages/sections/catalogue-solutions/catalogue-solutions/controller.js, app/pages/sections/catalogue-solutions/select/price/controller.js, app/pages/sections/catalogue-solutions/select/recipient/controller.js, app/pages/sections/catalogue-solutions/select/solution/controller.js, app/pages/sections/commencement-date/controller.js, app/pages/sections/description/controller.js, app/pages/sections/ordering-party/controller.js, app/pages/sections/service-recipients/controller.js, app/pages/sections/supplier/controller.js, app/pages/sections/supplier/search/controller.js, app/pages/sections/supplier/supplier/controller.js, app/pages/task-list/controller.js
Story [AB#7461](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/7461)
Task [AB#7666](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/7666)
=> structure endpoints by api

app/helpers/createAuthProvider.js
Story [AB#7395](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/7395)
Task [AB#7711](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/7711)
=> update authenticated error message

charts/of/templates/_helpers.tpl
[AB#6636](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/6636)
[AB#7440](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/7440)
=> Use local repository even when useLocalImage=false

app/pages/sections/catalogue-solutions/order-item/contextCreator.js, app/pages/sections/catalogue-solutions/order-item/controller.js, app/pages/sections/catalogue-solutions/order-item/controller.test.js, app/pages/sections/catalogue-solutions/order-item/manifest.json, app/pages/sections/catalogue-solutions/order-item/template.njk, app/pages/sections/catalogue-solutions/order-item/template.test.js, app/pages/sections/catalogue-solutions/order-item/ui-tests/general.ui.test.js, app/pages/sections/catalogue-solutions/routes.js, app/pages/sections/description/manifest.json, package-lock.json, package.json
Story [AB#4632](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/4632)
Task [AB#7717](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/7717)
=> 4632 show delivery quantity estimation

app/pages/sections/catalogue-solutions/order-item/template.njk, app/pages/sections/catalogue-solutions/order-item/template.test.js, package-lock.json, package.json
Task [AB#7717](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/7717)
=> pass custom width for quanity fieled

app/endpoints.js, app/pages/sections/catalogue-solutions/order-item/controller.js, app/pages/sections/catalogue-solutions/order-item/controller.test.js, app/pages/sections/catalogue-solutions/order-item/ui-tests/general.ui.test.js, app/pages/sections/catalogue-solutions/routes.js
Task [AB#7719](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/7719)
=> 7840 call bapi

app/pages/sections/catalogue-solutions/select/routes.js, app/pages/sections/catalogue-solutions/select/solution/contextCreator.js, app/pages/sections/catalogue-solutions/select/solution/contextCreator.test.js, app/pages/sections/catalogue-solutions/select/solution/ui-tests/general.ui.test.js
Story [AB#7826](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/7826)
Task [AB#7842](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/7842)
=> select solution on go back

app/pages/sections/catalogue-solutions/select/price/contextCreator.js, app/pages/sections/catalogue-solutions/select/price/contextCreator.test.js, app/pages/sections/catalogue-solutions/select/price/ui-tests/general.ui.test.js, app/pages/sections/catalogue-solutions/select/routes.js
Story [AB#7839](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/7839)
Task [AB#7843](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/7843)
=> show selected price on go back

app/pages/sections/catalogue-solutions/order-item/manifest.json, app/pages/sections/catalogue-solutions/order-item/template.njk, app/pages/sections/catalogue-solutions/order-item/template.test.js, app/pages/sections/catalogue-solutions/order-item/ui-tests/general.ui.test.js, package-lock.json, package.json
Task [AB#7718](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/7718)
=> 7840 added table

app/endpoints.js, app/pages/sections/catalogue-solutions/order-item/contextCreator.js, app/pages/sections/catalogue-solutions/order-item/contextCreator.test.js, app/pages/sections/catalogue-solutions/order-item/manifest.json, app/pages/sections/catalogue-solutions/order-item/ui-tests/general.ui.test.js, app/pages/sections/catalogue-solutions/select/price/controller.test.js, app/pages/sections/catalogue-solutions/select/price/ui-tests/general.ui.test.js
Task [AB#7720](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/7720)
=> 7840 populate form

app/helpers/routerHelper.js, app/pages/sections/catalogue-solutions/routes.js, app/pages/sections/catalogue-solutions/select/price/contextCreator.js, app/pages/sections/catalogue-solutions/select/price/ui-tests/general.ui.test.js, app/pages/sections/catalogue-solutions/select/routes.js, app/pages/sections/routes.js, app/pages/sections/supplier/routes.js, app/routes.js
Story [AB#7826](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/7826)
Task [AB#8048](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/8048)
=> ignore case on check of type

app/pages/sections/catalogue-solutions/select/price/manifest.json, app/pages/sections/catalogue-solutions/select/price/ui-tests/general.ui.test.js
Story [AB#7826](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/7826)
Task [AB#8074](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/8074)
=> content change

app/helpers/questionExtractor.js, app/helpers/questionExtractor.test.js, app/pages/sections/catalogue-solutions/order-item/contextCreator.js, app/pages/sections/catalogue-solutions/order-item/contextCreator.test.js, app/pages/sections/catalogue-solutions/order-item/controller.js, app/pages/sections/catalogue-solutions/order-item/controller.test.js, app/pages/sections/catalogue-solutions/order-item/manifest.json, app/pages/sections/catalogue-solutions/order-item/template.njk, app/pages/sections/catalogue-solutions/order-item/template.test.js, app/pages/sections/catalogue-solutions/order-item/ui-tests/general.ui.test.js, app/pages/sections/catalogue-solutions/routes.js, app/pages/sections/catalogue-solutions/routes.test.js, app/pages/sections/getSectionErrorContext.js, package-lock.json
Task [AB#7722](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/7722)
=> 7840 fe validation

app/pages/sections/catalogue-solutions/select/routes.js
Bug: [AB#8097](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/8097)
Task: [AB#8179](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/8179)
=> Convert selected price ID to number

app/pages/sections/additional-services/routes.js, app/pages/sections/additional-services/routes.test.js, app/pages/sections/routes.js
Story [AB#5124](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/5124)
Task [AB#8148](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/8148)
=> 5124: created routes for additional-services

app/pages/sections/commencement-date/controller.js, app/pages/sections/commencement-date/controller.test.js, app/pages/sections/routes.js, app/pages/sections/routes.test.js
=> extract FE validation out from putCommencementDate function

app/pages/preview/contextCreator.js
[AB#8216](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/8216)
[AB#8238](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/8238)
=> fix to preview for supplier & call off party being blank

app/pages/sections/additional-services/select/additional-service/ui-tests/general.ui.test.js
Story: [AB#5352](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/5352)
Task: [AB#8162](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/8162)
Looks like we got this one pretty much for free 😎
=> Fix test data

app/pages/preview/contextCreator.js, app/pages/preview/contextCreator.test.js
[AB#8216](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/8216)
[AB#8244](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/8244)
=> fixed tables & tests

app/pages/preview/ui-tests/withSavedData.ui.test.js
[AB#7898](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/7898)
[AB#7694](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/7694)
=> added declarative flat example to ui tests

app/pages/sections/catalogue-solutions/order-item/contextCreator.js, app/pages/sections/catalogue-solutions/order-item/contextCreator.test.js, app/pages/sections/catalogue-solutions/order-item/controller.js, app/pages/sections/catalogue-solutions/order-item/flat/ondemand/ui-tests/withSavedData.ui.test.js, app/pages/sections/catalogue-solutions/order-item/ui-tests/general.ui.test.js, app/pages/sections/catalogue-solutions/routes.js, app/pages/sections/catalogue-solutions/select/recipient/contextCreator.js, app/pages/sections/catalogue-solutions/select/recipient/contextCreator.test.js, app/pages/sections/catalogue-solutions/select/recipient/ui-tests/general.ui.test.js, app/pages/sections/catalogue-solutions/select/routes.js
Story [AB#8119](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/8119)
Task [AB#7857](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/7857)
=> go back link navigation

app/pages/sections/catalogue-solutions/order-item/flat/declarative/manifest.json, app/pages/sections/catalogue-solutions/order-item/flat/declarative/ui-tests/general.ui.test.js, app/pages/sections/catalogue-solutions/order-item/flat/declarative/ui-tests/withSavedData.ui.test.js, app/pages/sections/catalogue-solutions/order-item/flat/declarative/ui-tests/withoutSavedData.ui.test.js
[AB#8172](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/8172)
[AB#8173](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/8173)
[AB#7396](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/7396)
=> added declarative manifest and unit tests

app/pages/dashboard/contextCreator.test.js, app/pages/dashboard/manifest.json, app/pages/dashboard/template.njk, app/pages/dashboard/template.test.js, app/pages/dashboard/ui-tests/ui.test.js
Story [AB#8063](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/8063)
Task [AB#8313](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/8313)
=> remove proxy link

app/pages/sections/catalogue-solutions/order-item/contextCreator.js, app/pages/sections/catalogue-solutions/order-item/ui-tests/general.ui.test.js, app/pages/sections/catalogue-solutions/routes.js
Story [AB#8119](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/8119)
Task [AB#8337](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/8337)
=> fixed delete button not being disabled

app/pages/sections/additional-services/select/price/contextCreator.js, app/pages/sections/additional-services/select/price/contextCreator.test.js, app/pages/sections/additional-services/select/price/controller.js, app/pages/sections/additional-services/select/price/manifest.json, app/pages/sections/additional-services/select/price/template.njk, app/pages/sections/additional-services/select/price/template.test.js, app/pages/sections/additional-services/select/price/ui-tests/general.ui.test.js, app/pages/sections/additional-services/select/routes.js, app/pages/sections/additional-services/select/routes.test.js
Story: [AB#7264](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/7264)
Tasks: [AB#8272](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/8272), [AB#8273](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/8273), [AB#8274](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/8274)
=> Add additional service select price page

app/pages/sections/additional-services/routes.test.js, app/pages/sections/additional-services/select/routes.js
Story: [AB#7265](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/7265)
Task: [AB#8324](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/8324)
=> Add select additional services select recipient route

app/pages/sections/additional-services/order-item/contextCreator.test.js, app/pages/sections/additional-services/order-item/flat/declarative/ui-tests/general.ui.test.js, app/pages/sections/additional-services/order-item/flat/ondemand/ui-tests/general.ui.test.js, app/pages/sections/additional-services/order-item/flat/patient/manifest.json, app/pages/sections/additional-services/order-item/flat/patient/ui-tests/general.ui.test.js, app/pages/sections/additional-services/order-item/flat/patient/ui-tests/withSavedData.ui.test.js, app/pages/sections/additional-services/order-item/flat/patient/ui-tests/withoutSavedData.ui.test.js, app/pages/sections/catalogue-solutions/order-item/flat/declarative/ui-tests/general.ui.test.js, app/pages/sections/catalogue-solutions/order-item/flat/ondemand/ui-tests/general.ui.test.js, app/pages/sections/catalogue-solutions/order-item/flat/patient/ui-tests/general.ui.test.js
Story [AB#7584](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/7584)
Task [AB#8292](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/8292) [AB#8293](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/8293)
=> add manifest and ui tests for flat patient additional services

app/helpers/api/ordapi/getRecipients.js, app/helpers/api/ordapi/getRecipients.test.js, app/pages/sections/additional-services/select/recipient/ui-tests/general.ui.test.js, app/pages/sections/additional-services/select/routes.js, app/pages/sections/additional-services/select/routes.test.js, app/pages/sections/catalogue-solutions/select/recipient/controller.js, app/pages/sections/catalogue-solutions/select/recipient/controller.test.js, app/pages/sections/catalogue-solutions/select/routes.js, app/pages/sections/catalogue-solutions/select/routes.test.js
Story [AB#7265](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/7265)
Task [AB#8326](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/8326)
=> get recipients

app/pages/sections/additional-services/select/recipient/contextCreator.js, app/pages/sections/additional-services/select/recipient/contextCreator.test.js, app/pages/sections/additional-services/select/recipient/manifest.json, app/pages/sections/additional-services/select/recipient/template.njk, app/pages/sections/additional-services/select/recipient/template.test.js, app/pages/sections/additional-services/select/recipient/ui-tests/general.ui.test.js, app/pages/sections/additional-services/select/routes.js
Story [AB#7265](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/7265)
Task [AB#8327](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/8327)
=> add radio buttons

app/pages/sections/order-items/additional-services/select/recipient/contextCreator.js, app/pages/sections/order-items/additional-services/select/recipient/contextCreator.test.js, app/pages/sections/order-items/additional-services/select/routes.js, app/pages/sections/order-items/catalogue-solutions/select/recipient/contextCreator.test.js
Story [AB#7265](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/7265)
Task [AB#8331](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/8331)
=> populate selected recipient

app/pages/sections/order-items/additional-services/select/routes.js
Story: [AB#7264](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/7264)
Task: [AB#8278](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/8278)
=> Correct session key

app/pages/task-list/existingorder/ui-tests/ui.test.js, app/pages/task-list/helpers/generateTaskList.js, app/pages/task-list/helpers/generateTaskList.test.js, app/pages/task-list/neworder/ui-tests/ui.test.js, app/pages/task-list/taskListManifest.json
Story [AB#4829](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/4829)
=> 4829: Display associated services on order form

app/endpoints.js
Story: [AB#7263](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/7263)
Task: [AB#8518](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/8518)
=> 7263: Remove getAddedAdditionalService

app/pages/sections/order-items/associated-services/routes.js, app/pages/sections/order-items/associated-services/select/associated-service/contextCreator.js, app/pages/sections/order-items/associated-services/select/associated-service/contextCreator.test.js, app/pages/sections/order-items/associated-services/select/associated-service/controller.js, app/pages/sections/order-items/associated-services/select/associated-service/controller.test.js, app/pages/sections/order-items/associated-services/select/associated-service/manifest.json, app/pages/sections/order-items/associated-services/select/associated-service/template.njk, app/pages/sections/order-items/associated-services/select/associated-service/template.test.js, app/pages/sections/order-items/associated-services/select/associated-service/ui-tests/general.ui.test.js, app/pages/sections/order-items/associated-services/select/routes.js, app/pages/sections/order-items/associated-services/select/routes.test.js
Task: [AB#8419](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/8419)
=> Add select associated service basic page

app/endpoints.js, app/helpers/api/bapi/getCatalogueItemPricing.js, app/helpers/api/bapi/getCatalogueItemPricing.test.js, app/pages/sections/order-items/additional-services/select/price/controller.js, app/pages/sections/order-items/additional-services/select/price/controller.test.js, app/pages/sections/order-items/additional-services/select/routes.js, app/pages/sections/order-items/additional-services/select/routes.test.js, app/pages/sections/order-items/associated-services/routes.js, app/pages/sections/order-items/associated-services/select/price/contextCreator.js, app/pages/sections/order-items/associated-services/select/price/contextCreator.test.js, app/pages/sections/order-items/associated-services/select/price/controller.js, app/pages/sections/order-items/associated-services/select/price/manifest.json, app/pages/sections/order-items/associated-services/select/price/template.njk, app/pages/sections/order-items/associated-services/select/price/template.test.js, app/pages/sections/order-items/associated-services/select/price/ui-tests/general.ui.test.js, app/pages/sections/order-items/associated-services/select/routes.js, app/pages/sections/order-items/associated-services/select/routes.test.js
Story [AB#7072](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/7072)
Task [AB#8429](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/8429)
=> 7072 create basic page

app/helpers/api/bapi/getCatalogueItems.js, app/helpers/api/bapi/getCatalogueItems.test.js, app/pages/sections/order-items/associated-services/routes.js, app/pages/sections/order-items/associated-services/select/associated-service/controller.js, app/pages/sections/order-items/associated-services/select/associated-service/ui-tests/general.ui.test.js, app/pages/sections/order-items/associated-services/select/routes.js, app/pages/sections/order-items/associated-services/select/routes.test.js
Task: [AB#8421](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/8421)
=> Get associated services from BAPI

app/helpers/api/ordapi/postOrderItem.js, app/helpers/api/ordapi/postOrderItem.test.js, app/helpers/controllers/saveOrderItem.js, app/helpers/controllers/saveOrderItem.test.js, app/helpers/routes/getOrderItemPageData.js, app/helpers/routes/getOrderItemPageData.test.js, app/pages/sections/order-items/additional-services/order-item/flat/declarative/ui-tests/general.ui.test.js, app/pages/sections/order-items/additional-services/order-item/flat/declarative/ui-tests/withoutSavedData.ui.test.js, app/pages/sections/order-items/additional-services/order-item/flat/ondemand/ui-tests/general.ui.test.js, app/pages/sections/order-items/additional-services/order-item/flat/ondemand/ui-tests/withoutSavedData.ui.test.js, app/pages/sections/order-items/additional-services/order-item/flat/patient/ui-tests/general.ui.test.js, app/pages/sections/order-items/additional-services/order-item/flat/patient/ui-tests/withoutSavedData.ui.test.js, app/pages/sections/order-items/additional-services/routes.js, app/pages/sections/order-items/additional-services/select/additional-service/ui-tests/general.ui.test.js, app/pages/sections/order-items/additional-services/select/routes.js, app/pages/sections/order-items/additional-services/select/routes.test.js
Story [AB#7580](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/7580)
Task [AB#8539](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/8539)
=> pass catalogueSolutionId to post for additional-services

app/pages/sections/order-items/additional-services/order-item/controller.test.js, app/pages/sections/order-items/associated-services/order-item/contextCreator.js, app/pages/sections/order-items/associated-services/order-item/contextCreator.test.js, app/pages/sections/order-items/associated-services/order-item/controller.js, app/pages/sections/order-items/associated-services/order-item/controller.test.js, app/pages/sections/order-items/associated-services/order-item/flat/declarative/ui-tests/general.ui.test.js, app/pages/sections/order-items/associated-services/order-item/flat/declarative/ui-tests/withSavedData.ui.test.js, app/pages/sections/order-items/associated-services/order-item/flat/declarative/ui-tests/withoutSavedData.ui.test.js, app/pages/sections/order-items/associated-services/routes.js, app/pages/sections/order-items/catalogue-solutions/order-item/controller.test.js
Story: [AB#4832](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/4832)
Task: [AB#8543](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/8543)
=> Feature/4832 Add post route and UI tests

app/pages/sections/order-items/associated-services/order-item/flat/ondemand/manifest.json
Story: [AB#7569](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/7569)
Task: [AB#8452](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/8452)
=> 7569: Create manifest

app/pages/sections/order-items/associated-services/order-item/flat/ondemand/ui-tests/general.ui.test.js, app/pages/sections/order-items/associated-services/order-item/flat/ondemand/ui-tests/withSavedData.ui.test.js, app/pages/sections/order-items/associated-services/order-item/flat/ondemand/ui-tests/withoutSavedData.ui.test.js
Story: [AB#7569](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/7569)
Task: [AB#8454](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/8454)
=> 7569: UI Tests

app/helpers/contextCreators/generateAddPriceTable.js, app/helpers/contextCreators/generateAddPriceTable.test.js, app/pages/sections/order-items/additional-services/order-item/contextCreator.test.js, app/pages/sections/order-items/additional-services/order-item/flat/declarative/ui-tests/general.ui.test.js, app/pages/sections/order-items/additional-services/order-item/flat/ondemand/ui-tests/general.ui.test.js, app/pages/sections/order-items/additional-services/order-item/flat/patient/ui-tests/general.ui.test.js, app/pages/sections/order-items/associated-services/order-item/contextCreator.test.js, app/pages/sections/order-items/associated-services/order-item/flat/declarative/ui-tests/general.ui.test.js, app/pages/sections/order-items/associated-services/order-item/flat/ondemand/ui-tests/general.ui.test.js, app/pages/sections/order-items/catalogue-solutions/order-item/contextCreator.test.js, app/pages/sections/order-items/catalogue-solutions/order-item/flat/declarative/ui-tests/general.ui.test.js, app/pages/sections/order-items/catalogue-solutions/order-item/flat/ondemand/ui-tests/general.ui.test.js, app/pages/sections/order-items/catalogue-solutions/order-item/flat/patient/ui-tests/general.ui.test.js
Story [AB#8534](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/8534)
Task [AB#8596](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/8596)
=> 0 value price fix

app/pages/task-list/existingorder/ui-tests/ui.test.js, app/pages/task-list/neworder/ui-tests/ui.test.js, app/pages/task-list/taskListManifest.json
Story [AB#5436](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/5436)
Task [AB#8593](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/8593)
=> added a new task list item

app/pages/sections/routes.js, app/pages/sections/routes.test.js
Story [AB#5437](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/5437)
Task [AB#8601](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/8601)
=> funding source route

app/helpers/api/bapi/getCatalogueItems.js, app/helpers/api/bapi/getCatalogueItems.test.js, app/helpers/api/ordapi/getSupplier.js, app/helpers/api/ordapi/getSupplier.test.js, app/pages/sections/order-items/associated-services/select/associated-service/contextCreator.js, app/pages/sections/order-items/associated-services/select/associated-service/contextCreator.test.js, app/pages/sections/order-items/associated-services/select/associated-service/controller.js, app/pages/sections/order-items/associated-services/select/associated-service/controller.test.js, app/pages/sections/order-items/associated-services/select/associated-service/ui-tests/general.ui.test.js, app/pages/sections/order-items/associated-services/select/routes.js, app/pages/sections/order-items/catalogue-solutions/select/routes.js
Task: [AB#8422](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/8422)
=> Display associated services for selection

app/pages/sections/order-items/associated-services/select/associated-service/ui-tests/general.ui.test.js, app/pages/sections/order-items/associated-services/select/routes.js, app/pages/sections/order-items/associated-services/select/routes.test.js
Tasks: [AB#8439](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/8439), [AB#8432](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/8432)
=> Add select associated service POST

app/pages/sections/order-items/associated-services/select/associated-service/contextCreator.js, app/pages/sections/order-items/associated-services/select/associated-service/contextCreator.test.js, app/pages/sections/order-items/associated-services/select/associated-service/controller.js, app/pages/sections/order-items/associated-services/select/associated-service/controller.test.js, app/pages/sections/order-items/associated-services/select/associated-service/ui-tests/general.ui.test.js, app/pages/sections/order-items/associated-services/select/routes.js, app/pages/sections/order-items/associated-services/select/routes.test.js
Task: [AB#8423](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/8423)
=> Add validation to select associated service page

app/pages/sections/funding-sources/contextCreator.js, app/pages/sections/funding-sources/contextCreator.test.js, app/pages/sections/funding-sources/controller.js, app/pages/sections/funding-sources/controller.test.js, app/pages/sections/funding-sources/manifest.json, app/pages/sections/funding-sources/template.njk, app/pages/sections/funding-sources/template.test.js, app/pages/sections/funding-sources/ui-tests/general.ui.test.js, app/pages/sections/routes.js, app/pages/sections/routes.test.js, app/pages/task-list/existingorder/ui-tests/ui.test.js
Story [AB#5437](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/5437)
Task [AB#8602](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/8602)
=> create basic page

app/pages/sections/order-items/associated-services/select/associated-service/ui-tests/general.ui.test.js, app/pages/sections/order-items/associated-services/select/routes.js, app/pages/sections/order-items/associated-services/select/routes.test.js
Task: [AB#8424](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/8424)
=> Display error page when no associated services

app/pages/sections/order-items/associated-services/select/associated-service/contextCreator.test.js
Task: [AB#8441](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/8441)
=> Add tests for selection on go back

app/helpers/api/ordapi/getFundingSource.js, app/helpers/api/ordapi/getFundingSource.test.js, app/pages/sections/funding-sources/contextCreator.js, app/pages/sections/funding-sources/contextCreator.test.js, app/pages/sections/funding-sources/controller.js, app/pages/sections/funding-sources/manifest.json, app/pages/sections/funding-sources/template.njk, app/pages/sections/funding-sources/template.test.js, app/pages/sections/funding-sources/ui-tests/general.ui.test.js, app/pages/sections/routes.js, app/pages/sections/routes.test.js
Story [AB#5437](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/5437)
Task [AB#8603](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/8603)
=> get funding source

app/pages/preview/ui-tests/withSavedData.ui.test.js
Story [AB#7696](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/7696)
Task [AB#8692](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/8692)
=> ui test to check associated service in recurring table

app/pages/sections/order-items/additional-services/order-item/flat/declarative/manifest.json, app/pages/sections/order-items/associated-services/order-item/flat/ondemand/manifest.json, app/pages/sections/order-items/catalogue-solutions/order-item/flat/declarative/manifest.json
Story [AB#5126](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/5126) [AB#8722](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/8722)
Task [AB#8732](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/8732) [AB#8725](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/8725)
Screenshot for 5126 8732 updated content for associated service on demand
Screenshot for 8722 8725 updated content for additional service declarative
=> update content for quantity expanded section

app/pages/sections/order-items/additional-services/routes.js, app/pages/sections/order-items/additional-services/select/routes.js, app/pages/sections/order-items/associated-services/routes.js, app/pages/sections/order-items/associated-services/select/routes.js, app/pages/sections/order-items/catalogue-solutions/routes.js
Story [AB#8737](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/8737)
Task [AB#8744](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/8744)
=> update session keys and clear session on succesfull post

app/helpers/api/ordapi/putFundingSource.js, app/helpers/api/ordapi/putFundingSource.test.js, app/pages/sections/funding-sources/controller.js, app/pages/sections/funding-sources/controller.test.js, app/pages/sections/routes.test.js
Story [AB#5437](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/5437)
Task [AB#8612](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/8612)
=> fixed bug on put

app/pages/task-list/existingorder/ui-tests/ui.test.js, app/pages/task-list/taskListManifest.json, app/pages/task-list/taskListManifest.test.js
Story: [AB#5436](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/5436)
Task: [AB#8734](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/8734)
=> Fix enabling/disabling funding source in task list

app/helpers/api/ordapi/getOrder.js, app/helpers/api/ordapi/getOrder.test.js
Story [AB#7725](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/7725)
Task [AB#8776](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/8776)
=> only add orderItem when it exists

app/config.js, app/helpers/routes/routerHelper.js, app/pages/error/template.njk, package-lock.json, package.json
Tech debt task: [AB#8779](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/8779)
=> Add stack trace to error page in development

app/pages/preview/manifest.json
Story: [AB#7703](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/7703)
Task: [AB#8820](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/8820)
Task: [AB#8821](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/8821)
=> Feature/7703 Update the order preview page content

app/pages/preview/ui-tests/withSavedData.ui.test.js
Story [AB#7729](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/7729)
Task [AB#8824](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/8824)
=> sort one off cost order items

app/pages/task-list/contextCreator.js, app/pages/task-list/contextCreator.test.js, app/pages/task-list/existingorder/ui-tests/ui.test.js
Story [AB#5145](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/5145)
Task [AB#8826](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/8826)
=> linked submit button to complete-order page

app/pages/preview/manifest.json
Story [AB#8870](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/8870)
Task [AB#8946](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/8946)
=> updated content

app/pages/sections/routes.js
Story [AB#5145](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/5145)
Task [AB#8827](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/8827)
=> called ordapi

app/helpers/api/ordapi/getOrderDescription.test.js, app/helpers/routes/getOrderDescription.js, app/helpers/routes/getOrderDescription.test.js, app/helpers/routes/sessionHelper.js, app/pages/sections/description/controller.js, app/pages/sections/description/controller.test.js, app/pages/sections/order-items/additional-services/dashboard/controller.js, app/pages/sections/order-items/additional-services/dashboard/controller.test.js, app/pages/sections/order-items/additional-services/routes.js, app/pages/sections/order-items/associated-services/dashboard/controller.js, app/pages/sections/order-items/associated-services/dashboard/controller.test.js, app/pages/sections/order-items/associated-services/routes.js, app/pages/sections/order-items/catalogue-solutions/dashboard/controller.js, app/pages/sections/order-items/catalogue-solutions/dashboard/controller.test.js, app/pages/sections/order-items/catalogue-solutions/routes.js, app/pages/sections/routes.js
Activity: [AB#8866](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/8866)
Task: [AB#8868](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/8868)
=> Refactor to use new getOrderDescription function

app/pages/dashboard/contextCreator.js, app/pages/dashboard/contextCreator.test.js, app/pages/dashboard/manifest.json, app/pages/dashboard/template.njk, app/pages/dashboard/template.test.js, app/pages/dashboard/ui-tests/ui.test.js, app/test-utils/mockData/mockOrders.json
Story: [AB#5145](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/5145)
Story: [AB#8774](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/8774)
Task: [AB#8923](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/8923)
Task: [AB#8847](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/8847)
Task: [AB#8848](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/8848)
=> Feature/5145 Change order status names

app/pages/task-list/commonManifest.json, app/pages/task-list/contextCreator.js, app/pages/task-list/contextCreator.test.js, app/pages/task-list/existingorder/ui-tests/ui.test.js, app/pages/task-list/neworder/ui-tests/ui.test.js, app/pages/task-list/template.njk, app/pages/task-list/template.test.js
Story: [AB#8758](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/8758)
Task: [AB#8846](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/8846)
=> Feature/8758 Change submit order button text

app/pages/sections/routes.js
Activity: [AB#8867](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/8867)
Task: [AB#8869](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/8869)
=> Clear session when description is updated

app/routes.js, app/routes.test.js
Story [AB#5287](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/5287)
Task [AB#8856](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/8856)
=> add delete order route

app/pages/dashboard/contextCreator.js, app/pages/dashboard/contextCreator.test.js, app/pages/dashboard/manifest.json, app/pages/dashboard/template.njk
Story: [AB#8774](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/8774)
Task: [AB#8849](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/8849)
=> Use bcTableFlexible component instead of bcTable

app/pages/dashboard/contextCreator.js, app/pages/dashboard/contextCreator.test.js, app/pages/dashboard/manifest.json, app/pages/dashboard/template.njk, app/pages/dashboard/template.test.js, app/pages/dashboard/ui-tests/ui.test.js, app/test-utils/mockData/mockFormattedOrders.json, app/test-utils/mockData/mockOrders.json
Story: [AB#8774](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/8774)
Task: [AB#8850](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/8850)
=> Add automatically processed column

app/pages/sections/funding-source/manifest.json, app/pages/sections/funding-source/template.njk, app/pages/sections/funding-source/template.test.js, app/pages/sections/funding-source/ui-tests/general.ui.test.js
Story: [AB#8677](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/8677)
Task: [AB#8851](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/8851)
=> 8677: Update funding source page

app/pages/dashboard/manifest.json
Story: [AB#8774](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/8774)
Task: [AB#9027](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/9027)
=> feature/8774 Incorrect content in H2

app/pages/complete-order/order-confirmation/contextCreator.js, app/pages/complete-order/order-confirmation/contextCreator.test.js, app/pages/complete-order/order-confirmation/template.njk, app/pages/complete-order/order-confirmation/template.test.js, app/pages/complete-order/order-confirmation/withoutFundingManifest.json
Story: [AB#8735](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/8735)
Task: [AB#8838](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/8838)
=> Feature/8735 Add without funding order confirmation manifest

app/helpers/api/ordapi/putOrderStatus.js, app/helpers/api/ordapi/putOrderStatus.test.js, app/pages/complete-order/routes.js, app/pages/complete-order/routes.test.js, app/pages/complete-order/template.njk, app/pages/complete-order/template.test.js, app/pages/complete-order/ui-tests/general.ui.test.js
Story [AB#5145](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/5145)
Task [AB#8831](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/8831)
=> Post route

app/pages/delete-order/contextCreator.js, app/pages/delete-order/contextCreator.test.js, app/pages/delete-order/manifest.json, app/pages/delete-order/ui-tests/general.ui.test.js
Story: [AB#5287](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/5287)
Task: [AB#9219](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/9219)
=> 5287: Fix title bug

app/pages/dashboard/contextCreator.js, app/pages/dashboard/contextCreator.test.js, app/test-utils/mockData/mockOrders.json
Story: [AB#8741](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/8741)
Task: [AB#9080](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/9080)
=> 8741: Automatically processed FE

app/helpers/api/ordapi/getOrders.js, app/helpers/api/ordapi/getOrders.test.js, app/pages/dashboard/ui-tests/ui.test.js, app/test-utils/mockData/mockOrders.json
Story [AB#6859](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/6859)
Task [AB#9075](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/9075) [AB#9076](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/9076)
=> Sort orders by descending

app/pages/summary/routes.js, app/pages/summary/routes.test.js, app/routes.js, app/routes.test.js
Story [AB#8904](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/8904)
Task [AB#9087](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/9087)
=> refactored routes

app/pages/summary/contextCreator.js, app/pages/summary/contextCreator.test.js, app/pages/summary/incomplete/manifest.json, app/pages/summary/incomplete/ui-tests/general.ui.test.js, app/pages/summary/template.njk, app/pages/summary/template.test.js
Story: [AB#8739](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/8739)
Task: [AB#9083](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/9083)
=> 8739: Order summary button & content changes

app/helpers/app/isIdentityReady.js
Story [AB#8638](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/8638)
Task AB#9635
=> update wellknown endpoint

app/pages/dashboard/contextCreator.js, app/pages/dashboard/contextCreator.test.js, app/pages/dashboard/ui-tests/ui.test.js, app/pages/summary/complete/ui-tests/general.ui.test.js, app/pages/summary/contextCreator.js, app/pages/summary/contextCreator.test.js
Story [AB#8904](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/8904)
Task [AB#9092](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/9092)
=> updated link for complete order

app/pages/summary/complete/ui-tests/general.ui.test.js, app/pages/summary/contextCreator.js
Story [AB#8904](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/8904)
Task [AB#9414](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/9414)
=> fix complete date to only show date

app/endpoints.js, app/helpers/api/dapi/getDocumentByFileName.js, app/helpers/api/dapi/getDocumentByFileName.test.js, app/helpers/routes/routerHelper.js, app/routes.js, app/routes.test.js
Story [AB#9345](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/9345)
Task [AB#9046](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/9046)
=> moved dapi endpoint to helpers

app/endpoints.js, app/helpers/api/oapi/getOrganisation.js, app/helpers/api/oapi/getOrganisation.test.js, app/helpers/api/oapi/getServiceRecipients.js, app/helpers/api/oapi/getServiceRecipients.test.js, app/pages/sections/ordering-party/controller.js, app/pages/sections/service-recipients/controller.js, app/pages/sections/service-recipients/controller.test.js
Story [AB#9345](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/9345)
Task [AB#9047](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/9047)
=> moved oapi endpoints to helpers

app/pages/sections/order-items/catalogue-solutions/select/routes.js, app/pages/sections/order-items/catalogue-solutions/select/routes.test.js
Story [AB#9228](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/9228)
Task [AB#9326](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/9326)
=> update route when only one price

app/pages/sections/order-items/catalogue-solutions/select/price/ui-tests/general.ui.test.js, app/pages/sections/order-items/catalogue-solutions/select/routes.js
Story [AB#9228](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/9228)
Task [AB#9327](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/9327)
=> added ui test for only one price

app/helpers/routes/sessionHelper.js, app/pages/sections/order-items/catalogue-solutions/select/recipients/contextCreator.js, app/pages/sections/order-items/catalogue-solutions/select/recipients/contextCreator.test.js, app/pages/sections/order-items/catalogue-solutions/select/recipients/controller.js, app/pages/sections/order-items/catalogue-solutions/select/recipients/ui-tests/general.ui.test.js, app/pages/sections/order-items/catalogue-solutions/select/routes.js
Story [AB#9228](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/9228)
Task [AB#9328](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/9328)
[AB#9329](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/9329)
=> go back links

app/pages/sections/order-items/catalogue-solutions/select/recipients/contextCreator.test.js, app/pages/sections/order-items/catalogue-solutions/select/recipients/manifest.json
Story [AB#9766](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/9766)
Task [AB#9827](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/9827)
=> edit catalogue-solutions h2

app/helpers/api/ordapi/putPlannedDeliveryDate.js, app/helpers/api/ordapi/putPlannedDeliveryDate.test.js, app/helpers/routes/getServiceRecipients.js, app/helpers/routes/getServiceRecipients.test.js, app/helpers/routes/sessionHelper.js, app/pages/sections/order-items/catalogue-solutions/select/date/contextCreator.test.js, app/pages/sections/order-items/catalogue-solutions/select/date/controller.js, app/pages/sections/order-items/catalogue-solutions/select/date/controller.test.js, app/pages/sections/order-items/catalogue-solutions/select/date/manifest.json, app/pages/sections/order-items/catalogue-solutions/select/date/template.njk, app/pages/sections/order-items/catalogue-solutions/select/date/template.test.js, app/pages/sections/order-items/catalogue-solutions/select/date/ui-tests/general.ui.test.js, app/pages/sections/order-items/catalogue-solutions/select/recipients/contextCreator.js, app/pages/sections/order-items/catalogue-solutions/select/recipients/contextCreator.test.js, app/pages/sections/order-items/catalogue-solutions/select/recipients/controller.js, app/pages/sections/order-items/catalogue-solutions/select/recipients/controller.test.js, app/pages/sections/order-items/catalogue-solutions/select/routes.js
Fixes the following bugs:
- lowercase 'c' on continue button
- missing validation error message when date more than 183 weeks after commencement date
- missing validation error message when date before commencement date
- selected service recipients are not remembered when navigating back
Story: [AB#8952](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/8952)
Task: [AB#9982](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/9982)
=> Fix default delivery date bugs

app/helpers/routes/getOrderItemPageData.js, app/helpers/routes/getOrderItemPageData.test.js, app/pages/sections/order-items/catalogue-solutions/order-item/contextCreator.js, app/pages/sections/order-items/catalogue-solutions/order-item/contextCreator.test.js, app/pages/sections/order-items/catalogue-solutions/order-item/controller.js, app/pages/sections/order-items/catalogue-solutions/order-item/flat/patient/ui-tests/general.ui.test.js, app/pages/sections/order-items/catalogue-solutions/order-item/ui-tests/general.ui.test.js, app/pages/sections/order-items/catalogue-solutions/routes.js
Story [AB#8689](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/8689)
Task [AB#10087](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/10087)
=> fixed bug of too many recipients showing

app/pages/sections/order-items/catalogue-solutions/dashboard/contextCreator.js, app/pages/sections/order-items/catalogue-solutions/dashboard/contextCreator.test.js, app/pages/sections/order-items/catalogue-solutions/dashboard/manifest.json, app/pages/sections/order-items/catalogue-solutions/dashboard/template.test.js, app/pages/sections/order-items/catalogue-solutions/dashboard/ui-tests/withSavedData.ui.test.js
Story [AB#9030](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/9030)
Task [AB#10221](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/10221)
=> update catalogue dashboard

app/helpers/api/ordapi/postOrderItem.js, app/helpers/api/ordapi/postOrderItem.test.js, app/pages/sections/order-items/associated-services/order-item/flat/declarative/ui-tests/withoutSavedData.ui.test.js, app/pages/sections/order-items/associated-services/order-item/flat/ondemand/ui-tests/withoutSavedData.ui.test.js
Story: [AB#10328](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/10328)
Task: [AB#10341](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/10341)
=> Only include service recipient when required

package-lock.json, package.json
Story [AB#10110](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/10110)
Task [AB#10339](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/10339)
=> updated version

app/helpers/routes/getCommencementDate.js, app/helpers/routes/getCommencementDate.test.js, app/pages/sections/order-items/catalogue-solutions/select/routes.js, app/pages/sections/order-items/catalogue-solutions/select/routes.test.js
Story [AB#10110](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/10110)
Task [AB#10454](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/10454)
=> persist date bug

app/helpers/routes/getCommencementDate.js, app/helpers/routes/getCommencementDate.test.js
Story [AB#10110](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/10110)
Task [AB#10454](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/10454)
=> updated date

app/helpers/controllers/validateOrderItemFormBulk.js, app/helpers/controllers/validateOrderItemFormBulk.test.js, app/pages/sections/order-items/catalogue-solutions/order-item/flat/patient/manifest.json
Story: [AB#10507](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/10507)
Task: [AB#10455](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/10455)
=> Fix missing validation for list price bug

app/helpers/api/ordapi/postOrderItemBulk.js, app/helpers/api/ordapi/postOrderItemBulk.test.js
Task [AB#10516](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/10516)
Task [AB#10599](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/10599)
=> can now save an edited catalouge solution

app/helpers/routes/getOrderItemPageDataBulk.js, app/helpers/routes/getOrderItemPageDataBulk.test.js
Story [AB#10509](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/10509)
Task [AB#10622](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/10622)
=> practice size bug

app/pages/summary/complete/manifest.json, app/pages/summary/complete/ui-tests/general.ui.test.js, app/pages/summary/complete/ui-tests/withSavedData.ui.test.js
Story [AB#10684](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/10684)
Task [AB#10683](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/10683)
=> service instance for complete orders

app/pages/summary/template.test.js, app/pages/summary/templatePrint.test.js
Story [AB#10036](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/10036)
Task [AB#10726](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/10726)
=> added tests

app/helpers/api/bapi/getCatalogueItems.js, app/helpers/api/bapi/getCatalogueItems.test.js, app/pages/sections/order-items/associated-services/select/associated-service/ui-tests/general.ui.test.js, app/pages/sections/order-items/catalogue-solutions/select/solution/ui-tests/general.ui.test.js
Story [AB#10552](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/10552)
Task [AB#10759](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/10759)
=> filter bug

.gitattributes, Dockerfile, README.md, azure-pipelines.yml, package-lock.json, package.json
Update dependencies, use node 14, tidy readme and add .gitattributes.
Activities: [AB#11100](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/11100), [AB#11133](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/11133)
Tasks: [AB#11107](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/11107), [AB#11137](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/11137)
=> Update dependencies and use node 14

app/app.js
+semver:patch
Activity: [AB#11185](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/11185)
Task: [AB#11197](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/11197)
=> Disable helmet referrer policy

app/pages/summary/routes.js
=> inline print script requires security policy to allow

app/pages/sections/order-items/catalogue-solutions/order-item/contextCreator.js, app/pages/sections/order-items/catalogue-solutions/order-item/flat/declarative/ui-tests/withSavedData.ui.test.js, app/pages/sections/order-items/catalogue-solutions/order-item/flat/ondemand/ui-tests/withSavedData.ui.test.js, app/pages/sections/order-items/catalogue-solutions/order-item/flat/patient/ui-tests/withSavedData.ui.test.js, app/pages/sections/order-items/catalogue-solutions/order-item/ui-tests/general.ui.test.js, app/pages/sections/order-items/catalogue-solutions/routes.js
Story [AB#9363](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/9363)
Task [AB#12323](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/12323)
=> edit recipient link changes

app/pages/sections/order-items/catalogue-solutions/order-item/flat/declarative/manifest.json
Quantity - corrected details
Story: 9160
Task: 12462
=> Bulk Ordering - Flat Declarative edit form

app/pages/sections/order-items/catalogue-solutions/order-item/flat/contextCreator.js, app/pages/sections/order-items/catalogue-solutions/order-item/flat/contextCreator.test.js, app/pages/sections/order-items/catalogue-solutions/order-item/flat/template.njk
Quantity & Estimation Period:
validation error messages shown next to fields
Story: 12231
Task: 12463
=> Bulk Ordering - Flat Variable (On Demand)

app/pages/sections/order-items/catalogue-solutions/select/recipients/controller.js, app/pages/sections/order-items/catalogue-solutions/select/recipients/controller.test.js, app/pages/sections/order-items/catalogue-solutions/select/recipients/template.njk, app/pages/sections/order-items/catalogue-solutions/select/recipients/template.test.js, app/pages/sections/order-items/catalogue-solutions/select/routes.js, app/pages/sections/order-items/catalogue-solutions/select/routes.test.js
Edit Catalogue Solution - update action & link on Edit Recipients
Ordered methods alphabetically in controller.js
Story: 9363
Task: 12324
=> Flat Variable (Patient numbers)

app/pages/dashboard/template.njk
To be a caption
Task: [AB#12266](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/12266)
Story: [AB#12166](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/12166)
=> Refactor table heading

app/pages/sections/order-items/catalogue-solutions/order-item/flat/declarative/manifest.json
Story [AB#12235](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/12235)  
Task [AB#12461](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/12461)
Bug fix - changes in manifest.json
=> Validation and remove content

app/pages/sections/description/template.njk, app/pages/sections/description/template.test.js, app/pages/sections/description/ui-tests/general.ui.test.js
Story [AB#12166](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/12166)
Task [AB#12267](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/12267)
=> change h2 description to label, change to correct css class

app/pages/summary/template.njk
From right to left for accessibility
Task: [AB#12882](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/12882)
Story: [AB#12166](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/12166)
=> Move order summary button

app/pages/sections/order-items/catalogue-solutions/order-item/flat/declarative/manifest.json
Edit Catalogue Solution:
Corrected price description
Story: 9160
Task: 12462
=> Bulk Ordering - Flat Declarative

app/pages/sections/order-items/catalogue-solutions/order-item/flat/ondemand/manifest.json, app/pages/sections/order-items/catalogue-solutions/routes.js, app/pages/sections/order-items/catalogue-solutions/routes.test.js
Story [AB#12942](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/12942)
Task [AB#12914](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/12914)
=> bug fix - price autopopulate and content mismatch

app/helpers/controllers/manifestProvider.js, app/helpers/controllers/manifestProvider.test.js, app/pages/sections/order-items/catalogue-solutions/order-item/controller.js, app/pages/sections/order-items/catalogue-solutions/order-item/controller.test.js, app/pages/sections/order-items/catalogue-solutions/routes.js, app/pages/sections/order-items/catalogue-solutions/routes.test.js
Bug fix: display correct heading on validation error
Story: [AB#12941](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/12941)
Task: [AB#12918](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/12918)
=> Bulk Ordering - Flat Variable On Demand

app/helpers/api/ordapi/putPlannedDeliveryDate.js, app/helpers/api/ordapi/putPlannedDeliveryDate.test.js, app/pages/sections/order-items/catalogue-solutions/select/date/ui-tests/general.ui.test.js, app/pages/sections/order-items/catalogue-solutions/select/routes.js
Story [AB#13000](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/13000)
Task [AB#12985](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/12985)
=> priceId removed from plannedDeliveryDate endpoint

app/pages/sections/description/manifest.json, app/pages/sections/description/ui-tests/existingorder.ui.test.js, app/pages/sections/description/ui-tests/neworder.ui.test.js
Story [AB#13000](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/13000)
Task [AB#13001](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/13001)
=> corrected description validation on order create

app/pages/sections/commencement-date/template.test.js, app/pages/sections/commencement-date/ui-tests/general.ui.test.js, app/pages/sections/order-items/catalogue-solutions/order-item/flat/declarative/ui-tests/general.ui.test.js, app/pages/sections/order-items/catalogue-solutions/order-item/flat/declarative/ui-tests/withSavedData.ui.test.js, app/pages/sections/order-items/catalogue-solutions/order-item/flat/ondemand/ui-tests/general.ui.test.js, app/pages/sections/order-items/catalogue-solutions/order-item/flat/ondemand/ui-tests/withSavedData.ui.test.js, app/pages/sections/order-items/catalogue-solutions/order-item/flat/patient/ui-tests/general.ui.test.js, app/pages/sections/order-items/catalogue-solutions/order-item/flat/patient/ui-tests/withSavedData.ui.test.js, app/pages/sections/order-items/catalogue-solutions/select/date/template.test.js, app/pages/sections/order-items/catalogue-solutions/select/date/ui-tests/general.ui.test.js, app/pages/sections/order-items/catalogue-solutions/select/solution/template.test.js, app/pages/sections/order-items/catalogue-solutions/select/solution/ui-tests/general.ui.test.js, package-lock.json, package.json
Story: [AB#11214](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/11214)
Ticket: [AB#13088](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/13088)
=> Update nhsuk-frontend npm package

app/helpers/api/ordapi/postOrderItemBulk.js, app/helpers/api/ordapi/postOrderItemBulk.test.js, app/pages/sections/order-items/catalogue-solutions/order-item/flat/declarative/ui-tests/withSavedData.ui.test.js, app/pages/sections/order-items/catalogue-solutions/order-item/flat/declarative/ui-tests/withoutSavedData.ui.test.js, app/pages/sections/order-items/catalogue-solutions/order-item/flat/ondemand/ui-tests/withSavedData.ui.test.js, app/pages/sections/order-items/catalogue-solutions/order-item/flat/ondemand/ui-tests/withoutSavedData.ui.test.js, app/pages/sections/order-items/catalogue-solutions/order-item/flat/patient/ui-tests/withSavedData.ui.test.js, app/pages/sections/order-items/catalogue-solutions/order-item/flat/patient/ui-tests/withoutSavedData.ui.test.js
api contract has now changed so that rather than the /bulk url fragment its takes the item id and changes from a http post to a http put
=> update post request to a put with new endpoint url

app/helpers/routes/getOrderItemPageDataBulk.js, app/helpers/routes/getOrderItemPageDataBulk.test.js, app/pages/sections/order-items/catalogue-solutions/order-item/flat/declarative/ui-tests/withSavedData.ui.test.js, app/pages/sections/order-items/catalogue-solutions/order-item/flat/ondemand/ui-tests/withSavedData.ui.test.js, app/pages/sections/order-items/catalogue-solutions/order-item/flat/patient/ui-tests/withSavedData.ui.test.js, app/pages/sections/order-items/catalogue-solutions/routes.js
Story [AB#12939](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/12939)
Task [AB#13128](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/13128)
=> bug-fix-multiple-catalogue-solutions-edit

app/helpers/controllers/manifestProvider.js, app/helpers/controllers/manifestProvider.test.js
Set estimation period on edit catalogue solution
Story: [AB#12941](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/12941)
Task: [AB#12918](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/12918)
=> Save Catalogue Solution - Flat Variable On Demand

app/helpers/api/ordapi/getOrder.js, app/helpers/api/ordapi/getOrder.test.js, app/helpers/controllers/manifestProvider.js, app/helpers/controllers/manifestProvider.test.js, app/pages/summary/complete/ui-tests/withSavedData.ui.test.js, app/pages/summary/contextCreator.js, app/pages/summary/contextCreator.test.js, app/pages/summary/controller.js, app/pages/summary/controller.test.js, app/pages/summary/incomplete/ui-tests/withSavedData.ui.test.js, app/pages/summary/routes.js
Catered for new structure with service recipients in order items
Story: [AB#13000](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/13000)
Task: [AB#13108](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/13108)
=> Order Summary update

app/pages/summary/complete/ui-tests/withSavedData.ui.test.js, app/pages/summary/incomplete/ui-tests/withSavedData.ui.test.js
Story [AB#13181](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/13181)
Task [AB#13206](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/13206)
=> adjusted tabs to spaces to comply with lint

app/helpers/common/priceFormatter.js, app/helpers/common/priceFormatter.test.js, app/helpers/controllers/validateOrderItemFormBulk.js
Story [AB#12945](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/12945)
Task [AB#13189](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/13189)
=> price validation bug fix

app/helpers/api/bapi/getAdditionalServices.js, app/helpers/api/bapi/getAdditionalServices.test.js
Sort additional services
Story: [AB#9227](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/9227)
Task: [AB#13222](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/13222)
=> Display Additional Services in alphabetical order

app/helpers/routes/sessionHelper.js, app/pages/sections/order-items/catalogue-solutions/dashboard/contextCreator.js, app/pages/sections/order-items/catalogue-solutions/routes.js, app/pages/sections/order-items/catalogue-solutions/routes.test.js, app/pages/sections/order-items/catalogue-solutions/select/routes.js, app/pages/sections/order-items/catalogue-solutions/select/routes.test.js, app/pages/sections/order-items/catalogue-solutions/select/solution/ui-tests/general.ui.test.js
Story [AB#9324](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/9324)
Task [AB#13221](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/13221)
Task [AB#13238](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/13238)
=> save session on dashboard and redirect to edit page

charts/of/templates/ingress.yaml
Task: [AB#11823](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/11823)
Activity: [AB#13202](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/13202)
=> Ingress configuration updated to v1

app/config.js, app/helpers/routes/getAdditionalServicesContextItems.js, app/helpers/routes/getAdditionalServicesContextItems.test.js, app/pages/sections/order-items/additional-services/order-item/contextCreator.js, app/pages/sections/order-items/additional-services/order-item/contextCreator.test.js, app/pages/sections/order-items/additional-services/order-item/ui-tests/general.ui.test.js, app/pages/sections/order-items/additional-services/select/price/ui-tests/general.ui.test.js, app/pages/sections/order-items/additional-services/select/recipient/contextCreator.js, app/pages/sections/order-items/additional-services/select/recipient/controller.js, app/pages/sections/order-items/additional-services/select/recipients/manifest.json, app/pages/sections/order-items/additional-services/select/routes.js, app/pages/sections/order-items/additional-services/select/routes.test.js, app/pages/sections/order-items/catalogue-solutions/select/recipients/contextCreator.js, app/pages/sections/order-items/catalogue-solutions/select/recipients/contextCreator.test.js, app/pages/sections/order-items/catalogue-solutions/select/recipients/controller.js, app/pages/sections/order-items/catalogue-solutions/select/routes.js, azure-pipelines.yml, charts/of/templates/deployment.yaml
Show multiple recipients page with feature flag
Story: [AB#9257](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/9257)
Task: [AB#13283](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/13283)
=> Select Service Recipients for Additional Service

app/pages/sections/order-items/associated-services/order-item/flat/declarative/ui-tests/withSavedData.ui.test.js, app/pages/sections/order-items/associated-services/order-item/flat/declarative/ui-tests/withoutSavedData.ui.test.js, app/pages/sections/order-items/associated-services/order-item/flat/ondemand/ui-tests/withSavedData.ui.test.js, app/pages/sections/order-items/associated-services/order-item/flat/ondemand/ui-tests/withoutSavedData.ui.test.js, app/pages/sections/order-items/associated-services/routes.js, app/pages/sections/order-items/associated-services/routes.test.js
Bug: [AB#13000](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/13000)
Task: [AB#13362](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/13362)
=> Fix save associated service

charts/of/values.yaml
Story: [AB#9257](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/9257)
Task: [AB#13367](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/13367)
=> Add feature flags section to helm values

charts/of/values.yaml
Story: [AB#9257](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/9257)
Task: [AB#13367](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/13367)
=> Fix values.yaml

app/pages/sections/order-items/catalogue-solutions/order-item/commonManifest.json
Story: [AB#13366](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/13366)
Task: [AB#13390](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/13390)
=> Update content - Edit Catalogue Solution

app/helpers/api/bapi/getCatalogueItems.js, app/helpers/api/bapi/getCatalogueItems.test.js, app/pages/sections/order-items/associated-services/select/associated-service/ui-tests/general.ui.test.js, app/pages/sections/order-items/catalogue-solutions/select/solution/ui-tests/general.ui.test.js
Activity: [AB#13180](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/13180)
Task: [AB#13382](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/13382)
=> Publication status filter

package-lock.json, package.json
Ticket: [AB#13478](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/13478)
Story: [AB#13346](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/13346)
=> Upgrade nhsuk-frontend

.dockerignore, Dockerfile, package-lock.json, package.json
Activity: [AB#13380](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/13380)
Task: [AB#13502](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/13502)
Reduces image size to c. 195 MB.
=> Use alpine base image and reduce image size

app/pages/sections/order-items/additional-services/order-item/flat/additionalServicesPageModel.js, app/pages/sections/order-items/additional-services/order-item/flat/patient/ui-tests/additionalServicesPageModel.test.js, app/pages/sections/order-items/additional-services/order-item/flat/patient/ui-tests/general.ui.test.js
Unskipped tests.
Refactored testcafe tests using Page Model.
=> Refactor unit tests

app/pages/sections/order-items/additional-services/dashboard/contextCreator.js, app/pages/sections/order-items/additional-services/dashboard/contextCreator.test.js, app/pages/sections/order-items/additional-services/dashboard/controller.js, app/pages/sections/order-items/additional-services/dashboard/controller.test.js, app/pages/sections/order-items/additional-services/dashboard/manifest.json, app/pages/sections/order-items/additional-services/dashboard/template.njk, app/pages/sections/order-items/additional-services/dashboard/ui-tests/withSavedData.ui.test.js, app/pages/sections/order-items/additional-services/routes.js, app/pages/sections/order-items/additional-services/routes.test.js
Update route with back link, controller and tests.
Story: [AB#9273](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/9273), [AB#9554](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/9554)
Task: [AB#13549](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/13549), [AB#13550](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/13550), [AB#13551](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/13551)
=> List Saved Additional Services

app/pages/dashboard/manifest.json
Story [AB#9499](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/9499)
Task [AB#13659](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/13659)
=> Update column title in Completed orders table of Organisation's Orders Dashboard

app/pages/sections/order-items/additional-services/dashboard/contextCreator.js, app/pages/sections/order-items/additional-services/dashboard/contextCreator.test.js, app/pages/sections/order-items/additional-services/dashboard/controller.js, app/pages/sections/order-items/additional-services/dashboard/controller.test.js, app/pages/sections/order-items/additional-services/order-item/flat/patient/ui-tests/withSavedData.ui.test.js, app/pages/sections/order-items/additional-services/order-item/ui-tests/general.ui.test.js, app/pages/sections/order-items/additional-services/routes.js, app/pages/sections/order-items/additional-services/routes.test.js, app/pages/sections/order-items/additional-services/select/recipient/contextCreator.js, app/pages/sections/order-items/additional-services/select/recipient/contextCreator.test.js, app/pages/sections/order-items/additional-services/select/recipient/controller.js, app/pages/sections/order-items/additional-services/select/recipient/controller.test.js, app/pages/sections/order-items/additional-services/select/routes.js, app/pages/sections/order-items/additional-services/select/routes.test.js
Flat Variable (Patient numbers) type
Set links to edit and get back
Fixed text on delete button on edit Additional Service screen
Story: [AB#9442](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/9442)
Task: [AB#13552](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/13552), [AB#13554](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/13554)
=> Edit service recipient: saved Additional Service

app/pages/complete-order/order-confirmation/ui-tests/withFundingGeneral.ui.test.js, app/pages/complete-order/order-confirmation/withFundingManifest.json, app/pages/complete-order/withFundingManifest.json
Story: [AB#9490](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/9490)  
Task: [AB#13670](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/13670), [AB#13671](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/13671), [AB#13672](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/13672), [AB#13673](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/13673)
=> Add new content for funding source yes in complete order and add summary button

app/pages/summary/contextCreator.js, app/pages/summary/contextCreator.test.js
Story [AB#13476](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/13476)
Task [AB#13676](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/13676)
=> costPerYear now being displayed

app/pages/sections/order-items/additional-services/dashboard/contextCreator.js, app/pages/sections/order-items/additional-services/dashboard/contextCreator.test.js, app/pages/sections/order-items/additional-services/dashboard/controller.js, app/pages/sections/order-items/additional-services/dashboard/controller.test.js, app/pages/sections/order-items/additional-services/order-item/flat/patient/ui-tests/withSavedData.ui.test.js, app/pages/sections/order-items/additional-services/order-item/ui-tests/general.ui.test.js, app/pages/sections/order-items/additional-services/routes.js, app/pages/sections/order-items/additional-services/routes.test.js, app/pages/sections/order-items/additional-services/select/routes.js, app/pages/sections/order-items/additional-services/select/routes.test.js
Flat Variable (Patient numbers) type
Retain URLs on Select/Deselect all recipients
Story: [AB#9442](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/9442)
Task: [AB#13556](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/13556)
=> Edit service recipients: saved Additional Service

app/pages/sections/order-items/catalogue-solutions/dashboard/template.njk
Story [AB#13715](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/13715)
Task [AB#13754](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/13754)
=> remove two-thirds class

app/pages/sections/order-items/additional-services/dashboard/contextCreator.test.js, app/pages/sections/order-items/associated-services/order-item/contextCreator.js, app/pages/sections/order-items/associated-services/order-item/contextCreator.test.js, app/pages/sections/order-items/associated-services/order-item/controller.js, app/pages/sections/order-items/associated-services/order-item/controller.test.js, app/pages/sections/order-items/associated-services/order-item/flat/declarative/ui-tests/withSavedData.ui.test.js, app/pages/sections/order-items/associated-services/order-item/flat/ondemand/ui-tests/withSavedData.ui.test.js, app/pages/sections/order-items/associated-services/order-item/ui-tests/general.ui.test.js, app/pages/sections/order-items/associated-services/routes.js, app/pages/sections/order-items/associated-services/select/routes.js
Story [AB#9482](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/9482)
Task [AB#13710](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/13710)
Task [AB#13716](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/13716)
=> associated service single price

app/pages/sections/order-items/additional-services/dashboard/contextCreator.js, app/pages/sections/order-items/additional-services/dashboard/contextCreator.test.js, app/pages/sections/order-items/additional-services/dashboard/controller.js, app/pages/sections/order-items/additional-services/dashboard/controller.test.js, app/pages/sections/order-items/additional-services/routes.js, app/pages/sections/order-items/additional-services/routes.test.js
disabled buttons become enabled on validation message triggered
Corrected page display after POST validation
Story: [AB#13768](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/13768)
Task: [AB#13805](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/13805)
=> Additional services POST validation

app/pages/sections/order-items/associated-services/dashboard/contextCreator.js, app/pages/sections/order-items/associated-services/dashboard/contextCreator.test.js, app/pages/sections/order-items/associated-services/dashboard/manifest.json, app/pages/sections/order-items/associated-services/dashboard/ui-tests/withSavedData.ui.test.js
Story: [AB#13374](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/13374)
Task: [AB#13761](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/13761), [AB#13842](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/13842)
=> update associated service dashboard with unit and edit associated service

app/pages/sections/order-items/additional-services/dashboard/controller.js, app/pages/sections/order-items/additional-services/dashboard/controller.test.js, app/pages/sections/order-items/additional-services/order-item/contextCreator.test.js, app/pages/sections/order-items/additional-services/order-item/flat/additionalServicesPageModel.js, app/pages/sections/order-items/additional-services/order-item/flat/ondemand/manifest.json, app/pages/sections/order-items/additional-services/order-item/flat/ondemand/ui-tests/general.ui.test.js, app/pages/sections/order-items/additional-services/order-item/flat/patient/ui-tests/general.ui.test.js
Update manifest.json and unskip UI tests
Story: [AB#9451](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/9451)
Task: [AB#13849](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/13849)
=> Additional services Flat OnDemand

app/pages/sections/order-items/additional-services/dashboard/contextCreator.js, app/pages/sections/order-items/additional-services/dashboard/contextCreator.test.js, app/pages/sections/order-items/additional-services/dashboard/controller.js, app/pages/sections/order-items/additional-services/dashboard/controller.test.js, app/pages/sections/order-items/additional-services/dashboard/ui-tests/withSavedData.ui.test.js, app/pages/sections/order-items/additional-services/order-item/flat/ondemand/manifest.json, app/pages/sections/order-items/additional-services/order-item/flat/ondemand/ui-tests/withSavedData.ui.test.js, app/pages/sections/order-items/additional-services/order-item/flat/ondemand/ui-tests/withoutSavedData.ui.test.js, app/pages/sections/order-items/additional-services/order-item/flat/patient/ui-tests/withSavedData.ui.test.js, app/pages/sections/order-items/additional-services/order-item/ui-tests/general.ui.test.js, app/pages/sections/order-items/additional-services/routes.js
Story [AB#9448](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/9448)
Task [AB#13846](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/13846)
Task [AB#13888](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/13888)
=> save order item- ondemand

app/pages/sections/order-items/additional-services/select/routes.js, app/pages/sections/order-items/catalogue-solutions/select/routes.js
Story [AB#10462](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/10462)
Task [AB#13861](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/13861)
=> Previously selected Service Recipient persist resolved - bug-fix

app/pages/sections/order-items/catalogue-solutions/order-item/template.njk
Story [AB#13717](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/13717)
Task [AB#13720](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/13720)
reverted change from order-form/pull/528
=> Validation message highlighting more than one field

app/config.js, charts/of/templates/deployment.yaml, charts/of/values.yaml
Story [AB#12958](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/12958)
Task [AB#13822](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/13822)
=> add showProxy and SHOW_PROXY flag

app/pages/sections/order-items/additional-services/order-item/contextCreator.test.js, app/pages/sections/order-items/additional-services/order-item/flat/additionalServicesPageModel.js, app/pages/sections/order-items/additional-services/order-item/flat/declarative/manifest.json, app/pages/sections/order-items/additional-services/order-item/flat/declarative/ui-tests/general.ui.test.js, app/pages/sections/order-items/additional-services/order-item/flat/declarative/ui-tests/withSavedData.ui.test.js, app/pages/sections/order-items/additional-services/order-item/flat/declarative/ui-tests/withoutSavedData.ui.test.js, app/pages/sections/order-items/additional-services/order-item/flat/ondemand/ui-tests/general.ui.test.js
Updated manifest.json and tests
Story: [AB#9455](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/9455)
Task: [AB#13952](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/13952)
=> Edit form for Additional Service Flat Declarative

app/config.js, app/pages/dashboard/contextCreator.js, app/pages/dashboard/contextCreator.test.js, app/pages/dashboard/manifest.json, app/pages/dashboard/template.njk, app/pages/dashboard/template.test.js
Story [AB#12958](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/12958)
Task [AB#13821](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/13821)
=> show proxy "Order for" text if flag set

app/helpers/routes/getOrderItemPageDataBulk.js, app/helpers/routes/getOrderItemPageDataBulk.test.js, app/pages/sections/order-items/additional-services/select/routes.js
Bug - Incorrect catalogue item details saved
Set Catalogue Solution Id from Catalogue Solution
Story: [AB#14025](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/14025)
Task: [AB#14165](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/14165)
=> Edit Additional Service Recipients

app/pages/sections/order-items/additional-services/dashboard/controller.js, app/pages/sections/order-items/additional-services/dashboard/controller.test.js, app/pages/sections/order-items/additional-services/delete/confirmation/manifest.json, app/pages/sections/order-items/additional-services/delete/confirmation/ui-tests/general.ui.test.js, app/pages/sections/order-items/additional-services/delete/manifest.json, app/pages/sections/order-items/additional-services/delete/routes.js, app/pages/sections/order-items/additional-services/delete/routes.test.js, app/pages/sections/order-items/additional-services/delete/ui-tests/general.ui.test.js, app/pages/sections/routes.js
Story [AB#9464](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/9464)
Task [AB#14168](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/14168)
Task [AB#14171](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/14171)
=> delete additional services

app/pages/sections/order-items/additional-services/order-item/flat/declarative/manifest.json
Fixed planned delivery help text
Story: [AB#9455](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/9455)
Task: [AB#14121](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/14121)
=> Edit form: Additional Service Flat Declarative

app/helpers/common/transformApiValidationResponse.js, app/helpers/common/transformApiValidationResponse.test.js, app/helpers/controllers/getQuantityError.js, app/helpers/controllers/validateOrderItemForm.js, app/helpers/controllers/validateOrderItemForm.test.js, app/helpers/controllers/validateOrderItemFormBulk.js, app/helpers/controllers/validateOrderItemFormBulk.test.js, app/helpers/controllers/validateOrderItemTypeForm.js, app/pages/sections/order-items/associated-services/order-item/flat/declarative/ui-tests/withSavedData.ui.test.js, app/pages/sections/order-items/associated-services/order-item/flat/ondemand/ui-tests/withSavedData.ui.test.js, app/pages/sections/order-items/associated-services/order-item/flat/ondemand/ui-tests/withoutSavedData.ui.test.js
Correct & consolidate quantity validation for different types
Story: [AB#14163](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/14163)
Task: [AB#14195](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/14195)
=> Edit Page: Validation Error message not displayed

app/pages/sections/order-items/associated-services/delete/confirmation/manifest.json, app/pages/sections/order-items/associated-services/delete/confirmation/ui-tests/general.ui.test.js, app/pages/sections/order-items/associated-services/delete/manifest.json, app/pages/sections/order-items/associated-services/delete/routes.js, app/pages/sections/order-items/associated-services/delete/routes.test.js, app/pages/sections/order-items/associated-services/delete/ui-tests/general.ui.test.js, app/pages/sections/order-items/associated-services/order-item/contextCreator.js, app/pages/sections/order-items/associated-services/order-item/flat/declarative/ui-tests/withSavedData.ui.test.js, app/pages/sections/order-items/associated-services/order-item/flat/ondemand/ui-tests/withSavedData.ui.test.js, app/pages/sections/order-items/associated-services/order-item/ui-tests/general.ui.test.js, app/pages/sections/routes.js
Delete an Associated Service
Story: [AB#13376](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/13376)
Task: [AB#14108](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/14108), [AB#14109](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/14109)
=> Delete Associated Service

app/pages/sections/order-items/additional-services/dashboard/contextCreator.js, app/pages/sections/order-items/additional-services/dashboard/contextCreator.test.js, app/pages/sections/order-items/additional-services/dashboard/controller.js, app/pages/sections/order-items/additional-services/routes.js, app/pages/sections/order-items/additional-services/routes.test.js, app/pages/sections/order-items/additional-services/select/additional-service/ui-tests/general.ui.test.js, app/pages/sections/order-items/additional-services/select/routes.js, app/pages/sections/order-items/additional-services/select/routes.test.js
Story [AB#9289](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/9289)
Task [AB#14223](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/14223)
Task [AB#14222](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/14222)
=> additional service already in order

app/pages/sections/order-items/associated-services/dashboard/contextCreator.js, app/pages/sections/order-items/associated-services/routes.js, app/pages/sections/order-items/associated-services/routes.test.js, app/pages/sections/order-items/associated-services/select/associated-service/ui-tests/general.ui.test.js, app/pages/sections/order-items/associated-services/select/routes.js, app/pages/sections/order-items/associated-services/select/routes.test.js
Story [AB#13373](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/13373)
Task [AB#14255](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/14255)
Task [AB#14256](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/14256)
=> associated service in order

app/pages/sections/order-items/additional-services/select/routes.js, app/pages/sections/order-items/catalogue-solutions/select/recipients/controller.js, app/pages/sections/order-items/catalogue-solutions/select/recipients/controller.test.js, app/pages/sections/order-items/catalogue-solutions/select/routes.js
Ticket: [AB#14261](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/14261)
Story: [AB#7944](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/7944)
=> Fix select/deselect button

app/pages/sections/order-items/additional-services/delete/confirmation/ui-tests/general.ui.test.js, app/pages/sections/order-items/additional-services/delete/ui-tests/general.ui.test.js, app/pages/sections/order-items/associated-services/delete/confirmation/ui-tests/general.ui.test.js, app/pages/sections/order-items/associated-services/delete/ui-tests/general.ui.test.js, app/pages/sections/order-items/catalogue-solutions/delete/confirmation/template.njk, app/pages/sections/order-items/catalogue-solutions/delete/confirmation/ui-tests/general.ui.test.js, app/pages/sections/order-items/catalogue-solutions/delete/template.njk, app/pages/sections/order-items/catalogue-solutions/delete/template.test.js, app/pages/sections/order-items/catalogue-solutions/delete/ui-tests/general.ui.test.js
Story: [AB#14240](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/14240)
Ticket: [AB#14279](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/14279)
=> Refactor intro paragraph

app/helpers/routes/routerHelper.js, app/pages/error/template.njk, app/routes.js
Story: [AB#14240](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/14240)
Task: [AB#14271](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/14271)
=> Improve error message

app/pages/sections/order-items/associated-services/delete/confirmation/manifest.json, app/pages/sections/order-items/associated-services/delete/manifest.json
Ticket: [AB#14478](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/14478)
Story: [AB#14475](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/14475)
=> Update delete associated service message

app/helpers/controllers/validateOrderItemFormBulk.js, app/helpers/controllers/validateOrderItemFormBulk.test.js, app/helpers/routes/getOrderItemPageDataBulk.js, app/helpers/routes/getOrderItemPageDataBulk.test.js, app/pages/sections/order-items/additional-services/order-item/flat/declarative/ui-tests/withSavedData.ui.test.js, app/pages/sections/order-items/additional-services/order-item/flat/ondemand/ui-tests/withSavedData.ui.test.js, app/pages/sections/order-items/additional-services/order-item/flat/patient/ui-tests/withSavedData.ui.test.js, app/pages/sections/order-items/catalogue-solutions/order-item/flat/declarative/ui-tests/withSavedData.ui.test.js, app/pages/sections/order-items/catalogue-solutions/order-item/flat/ondemand/ui-tests/withSavedData.ui.test.js, app/pages/sections/order-items/catalogue-solutions/order-item/flat/patient/ui-tests/withSavedData.ui.test.js
Story: [AB#13185](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/13185)
Task: [AB#13275](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/13275)
=> Fix bulk price validation

app/pages/select/controller.js, app/pages/select/controller.test.js, app/pages/select/routes.test.js, app/pages/select/template.njk
Story [AB#12958](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/12958)
Task [AB#14695](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/14695)
=> add current organisation to radiolist

app/helpers/controllers/odsCodeLookup.js, app/helpers/controllers/odsCodeLookup.test.js, app/pages/sections/description/ui-tests/neworder.ui.test.js, app/pages/sections/order-items/additional-services/order-item/ui-tests/general.ui.test.js, app/pages/sections/order-items/associated-services/order-item/flat/declarative/ui-tests/withSavedData.ui.test.js, app/pages/sections/order-items/associated-services/order-item/flat/declarative/ui-tests/withoutSavedData.ui.test.js, app/pages/sections/order-items/associated-services/order-item/flat/ondemand/ui-tests/withSavedData.ui.test.js, app/pages/sections/order-items/associated-services/order-item/flat/ondemand/ui-tests/withoutSavedData.ui.test.js, app/pages/sections/order-items/catalogue-solutions/select/recipients/ui-tests/general.ui.test.js, app/pages/sections/ordering-party/ui-tests/general.ui.test.js, app/pages/sections/ordering-party/ui-tests/withSavedData.ui.test.js, app/pages/sections/ordering-party/ui-tests/withoutSavedData.ui.test.js, app/pages/sections/routes.js
Story [AB#14286](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/14286)
Task [AB#14694](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/14694)
=> unksipped ui test cases

app/helpers/routes/sessionHelper.js, app/pages/dashboard/contextCreator.js, app/pages/dashboard/contextCreator.test.js, app/pages/dashboard/controller.js, app/pages/dashboard/controller.test.js, app/pages/dashboard/routes.js, app/pages/dashboard/ui-tests/ui.test.js, app/pages/select/contextCreator.js, app/pages/select/controller.js, app/pages/select/controller.test.js, app/pages/select/manifest.json, app/pages/select/routes.js, app/pages/select/routes.test.js, app/pages/select/template.njk, app/routes.js, app/routes.test.js, app/test-utils/mockData/mockOrganisationData.json
Update order dashboard to use the organization details saved to session
Story: [AB#12958](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/12958)
Task: [AB#13894](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/13894)
=> View dashboard

app/helpers/controllers/validateOrderItemForm.js, app/helpers/routes/getOrderItemPageData.js, app/helpers/routes/getOrderItemPageData.test.js, app/helpers/routes/getOrderItemPageDataBulk.js, app/pages/sections/order-items/associated-services/order-item/flat/declarative/manifest.json, app/pages/sections/order-items/associated-services/order-item/flat/declarative/ui-tests/withSavedData.ui.test.js, app/pages/sections/order-items/associated-services/order-item/flat/ondemand/manifest.json, app/pages/sections/order-items/associated-services/order-item/flat/ondemand/ui-tests/withSavedData.ui.test.js
Task: [AB#14693](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/14693)
Story: [AB#9225](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/9225)
=> Add validation to associated price field

README.md
Story [AB#14613](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/14613)
Task [AB#14624](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/14624)
=> updated readme to document .env file

app/includes/footer.test.js, package-lock.json, package.json
Ticket: [AB#14636](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/14636)
Story: [AB#13179](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/13179)
=> Update buying catalogue components

app/includes/footer.test.js, app/includes/manifest.json
Ticket: [AB#14859](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/14859)
Story: [AB#14474](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/14474)
=> Update 'Capabilities and Standards models' footer link

app/pages/select/contextCreator.js, app/pages/select/controller.js, app/pages/select/controller.test.js, app/pages/select/routes.js, app/pages/select/routes.test.js
Org is Pre-selected on select page
Related Org Back Button landing on User Org page
Story: [AB#12958](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/12958)
Task: [AB#14858](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/14858)
=> View Dashboard - Bug Fixes

app/pages/dashboard/contextCreator.js, app/pages/dashboard/contextCreator.test.js, app/pages/select/controller.js, app/pages/select/controller.test.js, app/pages/select/routes.js, app/pages/select/routes.test.js
Wrong Dashboard - Back Button via order journey
Move selected ods code to URL to avoid session storage
Story: [AB#12959](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/12959)
Task: [AB#14868](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/14868)
=> Create Orders - Bug Fix

app/pages/sections/order-items/additional-services/select/routes.js, app/pages/sections/order-items/catalogue-solutions/select/routes.js, package-lock.json, package.json
Activity: [AB#14872](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/14872)
Task: [AB#14972](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/14972)
=> Address uncontrolled data in path expressions

app/pages/select/controller.js, app/pages/select/controller.test.js
Story [AB#14491](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/14491)
Task [AB#14973](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/14973)
=> removed org name from change org page

charts/of/templates/deployment.yaml
Story: [AB#7250](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/7250)
Task: [AB#15050](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/15050)
=> Fix helm feature flag

app/routes.js
Story [AB#14286](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/14286)
Task [AB#15059](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/15059)
=> redirect to primary org dashboard if no odscode in url

app/pages/sections/supplier/supplier/ui-tests/general.ui.test.js
Story [AB#15131](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/15131)
Task [AB#15194](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/15194)
=> unskipped tests
